version: "3"
services:
  springboot-app:
    image: springboot-app
    restart: always
    build: .
    ports:
      - 8082:8080
    environment:
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - D:\java\runner\db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: gift
      MYSQL_ROOT_PASSWORD: root



